### ISSUE TITLE
Module not working properly after 0.8.6

### ISSUE THREAD

**Issue by PedroCavati** [schultzcole/FVTT-Long-Rest-HD-Healing-5e#10]
Using the module after the 0.8.6 and, while it prompts the dialog for me to roll hit die in a long rest, it doesn't recovers any of my spended die.
Looking forward for a fix for this :)
Using foundry 0.8.6, dnd 5e 1.3.3 and Tidy 5e Sheet 0.5.1

**Comment by Avitale34** [comment]
Came here for same reason, hope for a fix soon!

**Comment by Naitbit** [comment]
I think there was an API change in https://github.com/schultzcole/FVTT-Long-Rest-HD-Healing-5e/blob/master/lr-hd-healing.js#L222

and now it would have to be something like `if (updateItems.length)  await this.updateEmbeddedDocuments("Item", updateItems);`

~I'm not making PR as I've never written any Foundry module so my confidence in knowing the API is low.~

**Comment by schultzcole** [comment]
Should be fixed in 3.0.0 (out shortly). Thanks @Naitbit for taking the initiative on fixing this issue!
