### ISSUE TITLE
[Incompatibility] Module not working nicely with 5eHelpers

### ISSUE THREAD

**Issue by tagnullde** [schultzcole/FVTT-Long-Rest-HD-Healing-5e#15]
![image](https://user-images.githubusercontent.com/44159008/131510682-39ab038c-c15b-4c00-a79a-d2e7401d5fbd.png)

![image](https://user-images.githubusercontent.com/44159008/131510973-39fa367b-72de-403a-8ae8-81ed5e53048c.png)

**Comment by trioderegion** [comment]
Is there broken functionality? 5e Helpers is indeed manually wrapping long and short rest, but it is simply for inspection of the results. We change nothing about how the core long/short rest works:

https://github.com/trioderegion/dnd5e-helpers/blob/cd84a1f15cdcf0c7e18fd17a89f365199ad63ff5/scripts/modules/RestEffects.js#L64

**Comment by schultzcole** [comment]
Is this an actual issue or just a potential conflict warning? If there is an actual problem happening please describe it in detail.

**Comment by tagnullde** [comment]
For now a only potential conflict warning on my end. If I encounter additional troubles I'll let you know.
Usually I reported "issues" like this and the mod-devs fixed "something". So I did the same here. ;)

**Comment by schultzcole** [comment]
Sounds good. I'm going to close this issue, but feel free to reopen it if something breaks.
