### ISSUE TITLE
Minor Feature - Total of recovered HP is not show on the chat card when click on the "Rest" button

### ISSUE THREAD

**Issue by p4535992** [schultzcole/FVTT-Long-Rest-HD-Healing-5e#2]
**Environment Details**

Foundry VTT Version: 0.7.1
Operating System: [Linux]
How Are You Using Foundry: [Linux,Native Application (Electron), Chrome]
Which Game System: Dungeons and Dragons 5th Edition, version 0.95
Modules Enabled?: yes
OS, Hosting, Browser (if applicable): Linux/Node/Chrome

**Description of the issue:**

After make my rolls and click on the "Rest button" the total of recovered HP is not show on the chat card when click on the "Rest" button, it remains to 0.

It woul be nice to se the total of recovered hp, like in the standard HP long rest of Foundry VTT.

**Comment by schultzcole** [comment]
Resolved by @DarKDinDoN's work in PR #4
