### ISSUE TITLE
Suggestion for a module setting

### ISSUE THREAD

**Issue by SlahtizKatz** [schultzcole/FVTT-Long-Rest-HD-Healing-5e#5]
First of all, this is a lovely module and is a life saver. My campaign focuses on exploration and resource management so having this option helped a lot.

I notice that now user can change the amount of resources regained during the long rest (quarter, half, or full).

I would like to suggest adding another option "**None**".

For example, for my game (also this is a location specific effect), I want people to regain spell slot using spell points, but only regain a certain amount of spell points depends on their exploration and resting location. Being able to click Long Rest and none of the Spell Slots are changing, then we can do a calculation on how much slots they regained would be important. Right now I have to do it manually, but being able to set Spell recovery to zero would be a huge help.

**Comment by schultzcole** [comment]
Hi @SlahtizKatz, thank you for the suggestion, it is a good one. I'll see if I can release an update with this soon

**Comment by schultzcole** [comment]
This feature has been added in 2.1.0
