### ISSUE TITLE
Suggestion: Add option to recover a fraction of hit points on long rest instead of all of them.

### ISSUE THREAD

**Issue by ctbritt** [schultzcole/FVTT-Long-Rest-HD-Healing-5e#9]
I'm running a harsh resting campaign. My long rest rules are as follows:
1) When players long rest, instead of getting all HP back, the get half of what they would get (i.e., if they have 20 max HP and are at 10, they get 5 hp back on a long rest.) This could also be scaled by GM's preference (quarter, half, three-quarter, all).  
2) They can supplement those HP by spending HD as with a Short Rest. 
3) They then get whatever fraction of HD back the GM has decided. 

Would this be possible?

**Comment by ctbritt** [comment]
I added some very kludgy code to this that accomplishes this. I added a hit point recovery fraction to the Settings panel, and made the math work in lr-hd-healing.js. It's really ugly, but I'll bet you could make it more elegant. this is a great module, and it does exactly what I want right now. Hope you don't mind me digging into it! 


[lr-hd-healing.js.txt](https://github.com/schultzcole/FVTT-Long-Rest-HD-Healing-5e/files/5935794/lr-hd-healing.js.txt)

**Comment by schultzcole** [comment]
I don't mind at all! Sorry I haven't responded to this issue yet; I've been focusing on other modules lately. This is a reasonable suggestion I think, but it will be a while before I can get the chance to approach it.

**Comment by ctbritt** [comment]
No worries! I’m glad I was able to contribute. I don’t really know how to make it a “real” contribution in GitHub, since I’m totally new to coding so I’ll leave this here for now. Glad I was able to help!

**Comment by schultzcole** [comment]
Hey, just a quick update here, I intend to re-focus more on this request after the next dnd5e release (1.3.0). That release should have some changes that will make development of this module much more pleasant!

**Comment by ctbritt** [comment]
Oh awesome! Looking forward to it, and thanks for all your hard work on these modules.

**Comment by schultzcole** [comment]
@ctbritt Ok, this has been added in 3.0.0 (out soon). I modified your change a bit to (a) make the default hit point recovery 0% (to maintain backwards compatibility with the old behavior) and (b) to account for some changes necessary for dnd5e 1.3.0 but it should do what it needs to do.

**Comment by ctbritt** [comment]
oh, awesome, thanks! My code was super amateurish and kludgy, and I'm sure yours is much better.

**Comment by ctbritt** [comment]
Squee! Works perfectly. Thanks!
